### PR TITLE
ci: update tools dependencies

### PR DESCRIPTION
**Pull request by cpanato**
- ci: update tools dependencies

### CODE REVIEW

**Comment by borikoss** [comment]
When this PR can be merged? The new version of helm/kind-action@v1.2.0 is actually required to solve the problem of deploying helm charts to the kind cluster. The old version of GH action helm/kind-action@v1.1.0 is broken, kind cluster doesn't come up. Error message: "0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate."

**Comment by cpanato** [comment]
> When this PR can be merged? The new version of helm/kind-action@v1.2.0 is actually required to solve the problem of deploying helm charts to the kind cluster. The old version of GH action helm/kind-action@v1.1.0 is broken, kind cluster doesn't come up. Error message: "0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate."

the kind-action is already released https://github.com/helm/kind-action/releases/tag/v1.2.0 this repo here is an example in how to use.

you can update your workflows with helm/kind-action@v1.2.0

**Comment by cpanato** [comment]
gently ping @davidkarlsen @scottrigby

**Comment by cpanato** [comment]
closing this as well, working in a new and updated one

**Pull request closed without merging**
